### ISSUE TITLE
Can i addListener after emit was fiered

### ISSUE THREAD

**Issue by muxahuk** [Wolfy87/EventEmitter#94]
Hello,

How can i change or improve your eventEmiter so that if i call addListener afer emit was called it still will be fiered on emit ??

```javascript
var EventEmitter = require( "events" ).EventEmitter;
var events = new EventEmitter();

events.on( 'filter', function() {
	console.log( 'filter 1' );
} );

var num = events.emit( 'filter' );

events.on( 'filter', function() {
	console.log( 'filter 2' );
} );
```

so what i need is that console.log fiers 2 times, but now it's just `filter 1` fiering

Any help ?

**Comment by Wolfy87** [comment]
An event can be emitted multiple times, so if you want the second listener
to be executed you need to emit the event again. If you want something that
will resolve / fire, then immediately call any other listeners that were
added then maybe you want promises instead? https://github.com/kriskowal/q
for example.

**Comment by muxahuk** [comment]
sorry, cant figure out what should i add to emit so that `filter 2` is console loged ..
```javascript
q.fcall( events.emit( 'filter' ) ).done( function() {
	console.log( 'done' );
} );
```

**Comment by Wolfy87** [comment]
You may actually have more luck opening a question on http://stackoverflow.com/, your problem is not with EventEmitter from what I can understand.

EventEmitter allows you to set up listeners for an event then emit them multiple times, just like a click event on a DOM element. My point with Q was that if you want something that only emits once and then keeps executing listeners you add, you probably want to use promises instead.

Once you resolve a promise any listeners you add after are executed immediately, which is what you seemed to want in your original question. I apologise if I'm not explaining this clearly enough, but this isn't a problem with EventEmitter.

```javascript
var EventEmitter = require( "events" ).EventEmitter;
var events = new EventEmitter();

events.on( 'filter', function() {
    console.log( 'filter 1' );
} );

var num = events.emit( 'filter' );

// Either move this `on` call above the emit, or add a second emit call under it.
// There is no was for this to work otherwise.
events.on( 'filter', function() {
    console.log( 'filter 2' );
} );
```
