### ISSUE TITLE
Request: Emit should include event type as the first argument for the callback

### ISSUE THREAD

**Issue by azaslavsky** [Wolfy87/EventEmitter#95]
I've noticed some other event emitting systems pass the event type as an argument to the callback, which can often be very useful is a single callback function is bound to multiple events.  This is what the formatting currently produces:

```javascript
var testCallback = function(type, data) {
  //Type should say 'testEvent', but instead includes the data object, and data is undefined!
};
var eventEmitterInstance = new EventEmitter();

eventEmitterInstance.on('testEvent', testCallback);
eventEmitterInstance.emit('testEvent', {foo: 'bar'});
```

Instead, to get the above working, you'd need to write the emitter like this:

```javascript
eventEmitterInstance.emit('testEvent', 'testEvent', {foo: 'bar'});
```

This seems needlessly repetitive.  I can understand if you don't want to change the existing API for the benefit of current users, but maybe some sort of extra method, like `emitWithType`, could be useful here?  I'm happy to write up a quick PR if you agree that it would be useful.

**Comment by Wolfy87** [comment]
Since you can bind a listener to any function whatsoever (which could behave differently when provided a truthy first argument! Never trust JavaScript) changing this could cause many things to fall apart in subtle ways. So yes, you're right I don't want to change the existing API in this way.

Adding a separate method would be one way but I am always weary of bloating it with things that are better suited to being a tiny function the user can use to interact with the EventEmitter object. It's just an object after all.

So you could [partially apply][] your listener with the event name. You could then automate that inside of a function.

I've just noticed that post I linked is exactly what we're talking about!

```javascript
this.on('tweet', this.handleStreamEvent.bind(this, 'tweet')); // from the post

function onWithEventName(ee, name, listener) {

    ee.on(name, bound);
}
```

[partially apply]: http://passy.svbtle.com/partial-application-in-javascript-using-bind

**Comment by azaslavsky** [comment]
Partial application is nice I suppose, but it doesn't really change the fact that I don't want to write teh event name twice.  Would you be amenable to a "flag setting" option, like `.setOnceReturnValue()`, that modified the behavior of "emit" to publish events with the type as the first parameter?  That way, the old API is still preserved, but firing something like `.setTypeAsLeadingParameter(true)` when loading EventEmitter would enable this behavior?

**Comment by Wolfy87** [comment]
Sorry I haven't replied to this, I am neglecting this repository, even if it doesn't actually have many issues. I don't think I want to add flags to change this kind of functionality. I would be more inclined if you couldn't achieve this with a wrapper function like the one in my previous comment.

The fact that it's easy to add this, quite specific, use case with a small function shows that it should be the job of the consumer to customise the API to their liking. You have to remember that a lot of people use this as a browser version of the node.js EventEmitter too, which does not do anything like that.

So I would highly recommend that you use a wrapper function that uses partial application if you really want this functionality. Thank you for your suggestion though!
